batch_size: 5012
beta1: 0.9
ckpts_dir: /home/vm/hand_ws/src/FFHNet/checkpoints
data_dir: /home/vm/data/ffhnet-data
ds_name: train
gpu_ids: [0]
grasp_data_file_name: ffhnet-grasp.h5
init_gain: 0.02
is_train: true
kl_coef: 0.005
latentD: 5
load_path: /home/vm/hand_ws/src/FFHNet/checkpoints/2021-03-31T12_54_25
lr: 0.0001
lr_policy: plateau
name: ffhnet_lr_0.0001_bs_5012_scale_1_latentd_5
num_bps_per_object: 5
num_epochs: 10
num_threads: 10
patience_lr_policy_plateau: 3
print_freq: 1
save_dir: /home/vm/hand_ws/src/FFHNet/checkpoints/2021-04-09T15_15_03-gen_01
save_epoch_freq: 1
save_latest_freq: 1
scale: 1
start_epoch: 1
threshold_lr_policy_plateau: 0.01
to_tensorboard: true
train_ffhevaluator: false
train_ffhgenerator: true
weight_decay: 0.0005
weight_init_type: xavier
